# Generated by Django 3.1.2 on 2020-10-17 13:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0002_auto_20201013_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='load_NLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NLP_bow', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='load_NLP2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NLP_clf', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
