# Generated by Django 3.1.2 on 2020-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0003_load_nlp_load_nlp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclassification',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskclassification',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='投稿時間'),
        ),
        migrations.AddField(
            model_name='taskclassification',
            name='deadline',
            field=models.DateTimeField(auto_now=True, verbose_name='〆切日時'),
        ),
    ]
