# Generated by Django 3.1.2 on 2020-10-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0004_auto_20201018_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskclassification',
            old_name='todo_text',
            new_name='item',
        ),
    ]
