# Generated by Django 3.1.2 on 2020-10-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0005_auto_20201018_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='pred_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_pred', models.CharField(max_length=50)),
                ('True_pred', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='taskclassification',
            name='todo_pred',
        ),
    ]
