# Generated by Django 3.1.2 on 2020-10-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0006_auto_20201018_0546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pred_db',
        ),
        migrations.AddField(
            model_name='taskclassification',
            name='True_pred',
            field=models.CharField(default='other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskclassification',
            name='todo_pred',
            field=models.CharField(default='other', max_length=50),
            preserve_default=False,
        ),
    ]
