# Generated by Django 3.1.2 on 2020-10-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0007_auto_20201018_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_nlp',
            name='NLP_bow',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='load_nlp2',
            name='NLP_clf',
            field=models.JSONField(),
        ),
    ]
