# Generated by Django 3.1.2 on 2020-10-18 01:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0008_auto_20201018_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load_nlp',
            name='NLP_bow',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='load_nlp2',
            name='NLP_clf',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
