# Generated by Django 3.1.2 on 2020-10-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpredict', '0009_auto_20201018_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load_nlp2',
            name='NLP_clf',
        ),
        migrations.AddField(
            model_name='load_nlp2',
            name='NLP_cld',
            field=models.JSONField(default='aaaa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='load_nlp',
            name='NLP_bow',
            field=models.JSONField(),
        ),
    ]
